### ISSUE TITLE
请问一下如何实现点状的二维码呢

### ISSUE THREAD

**Issue by fenglijunnb** [higker/qrcode-go#1]

**Comment by fenglijunnb** [comment]
![image](https://user-images.githubusercontent.com/48191768/92359098-427c2800-f11d-11ea-9bc5-d11c01ad1509.png)

**Comment by auula** [comment]
https://www.zhihu.com/question/56941063

**Comment by fenglijunnb** [comment]
你好，他这个是Ui 设计，如果我们用go 代码生成这样的样式，该怎么弄呢

**Comment by auula** [comment]
> 你好，他这个是Ui 设计，如果我们用go 代码生成这样的样式，该怎么弄呢
No solution yet，There is no solution yet. Replace every pixel and unit
